apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol_persistClaim
spec:
  volumeName: vol_persist
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi